- How to create a Null values in a data

- None

    - np.nan

In [1]:
import numpy as np
import pandas as pd

In [2]:
d = {'Names':['Ramesh','Suresh','None','Mahesh'],
     'Age':[None,22,24,25],
     'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df1

    Names   Age  City
0  Ramesh   NaN   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [3]:
df1.to_csv('data.csv',index=False)

In [4]:
d = {'Names':['Ramesh','Suresh','None','Mahesh'],
     'Age':[None,22,24,25],
     'City':['Hyd','Blr','Pune',None]}
df1=pd.DataFrame(d)
df2.to_csv('data2.csv',index=False)

NameError: name 'df2' is not defined

- Categorical data use None

- Numerical data use np.num

In [ ]:
np.nan + 10

In [ ]:
None + 10

In [5]:
df1.isnull()

# insull = wherever NUll value there it display as True

   Names    Age   City
0  False   True  False
1  False  False  False
2  False  False  False
3  False  False   True

In [6]:
df1.isnull().sum()

Names    0
Age      1
City     1
dtype: int64

In [7]:
df1
df1.values

array([['Ramesh', nan, 'Hyd'],
       ['Suresh', 22.0, 'Blr'],
       ['None', 24.0, 'Pune'],
       ['Mahesh', 25.0, None]], dtype=object)

In [8]:
df1
df1.dtypes

Names     object
Age      float64
City      object
dtype: object

In [9]:
df1
df1.isnull().sum()

Names    0
Age      1
City     1
dtype: int64

In [10]:
df1
df1.values
df1.dtypes
df1.isnull()
df1.isnull().sum()

Names    0
Age      1
City     1
dtype: int64

**Fill the values**

In [11]:
# Random fill automatic values

df1.fillna(30)

    Names   Age  City
0  Ramesh  30.0   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0    30

In [12]:
# Select one columns and will with value

df1['City'].fillna('Delhi')

0      Hyd
1      Blr
2     Pune
3    Delhi
Name: City, dtype: object

In [13]:
# pad ,ffill,bfill, ,backfill
# axis=0   axis=1
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

df1.fillna(method='bfill')
df1.fillna(method='bfill',axis=1)

C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1882744228.py:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')
C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1882744228.py:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)
C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1882744228.py:6: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill')
C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1882744228.py:7: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='bfill',axis=1)

    Names   Age  City
0  Ramesh   Hyd   Hyd
1  Suresh  22.0   Blr
2    None  24.0  Pune
3  Mahesh  25.0  None

In [14]:
df1.fillna(method='pad')
df1.fillna(method='pad',axis=1)

C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1394791076.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad')
C:\Users\hp-440 G6\AppData\Local\Temp\ipykernel_17376\1394791076.py:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df1.fillna(method='pad',axis=1)

    Names     Age  City
0  Ramesh  Ramesh   Hyd
1  Suresh    22.0   Blr
2    None    24.0  Pune
3  Mahesh    25.0  25.0

- mean 

- median

- modem

In [15]:
age_mean=df1['Age'].mean()
df1['Age'].fillna(age_mean)

0    23.666667
1    22.000000
2    24.000000
3    25.000000
Name: Age, dtype: float64

In [16]:
age_median=df1['Age'].median()
df1['Age'].fillna(age_median)

0    24.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [17]:
age_mode=df1['Age'].mode()
df1['Age'].fillna(age_mode)

0    22.0
1    22.0
2    24.0
3    25.0
Name: Age, dtype: float64

In [18]:
# there  is no perticular rule how to fille the missing value
# It is completety based on situation

In [19]:
Gender=['Male','Female',None]
d1=pd.DataFrame(Gender,columns=['Gender'])

In [20]:
d1 # I want to handover this data to my students with not encode

   Gender
0    Male
1  Female
2    None

In [21]:
# The student thik that I want to fill a missing
# data is numerical : mean
(1+0)/2

0.5

In [22]:
d=={'Female':0,'Male':1}
d1['Gender']=d1['Gender'].map(d)
d1

  Gender
0    NaN
1    NaN
2    NaN

**sitution-2**

In [23]:
# Ml algorithm
# churn :stay or not stay
churn=['stay','not_stay',None]
churn=[0,1,None]
churn=[0,1,0.5]

**Situation-3**

In [24]:
# no of days
[20,25,np.nan,31]
(20+25+31)/3

25.333333333333332

**Setution-4**

In [25]:
course=['DS','AI','DS','DEVOPS','AI','DEVLOPS','AI']
free=[30000,27000,30000,22000,30000,22000,np.nan]
pd.DataFrame(zip(course,free))

# first group by with course 
# then take corresponding course values only

         0        1
0       DS  30000.0
1       AI  27000.0
2       DS  30000.0
3   DEVOPS  22000.0
4       AI  30000.0
5  DEVLOPS  22000.0
6       AI      NaN

**KNNImputer**

- KNN: K-nearest neighbours

- where K is number

- instaed of taking avg of all the values data

    - first will find the neighbours who are close with missing data

    - by using Euclidian distance calculation will idenify the neighbour rows

    - suppose k=2 will identify the two closest rows

    - those closest rows values will take it, will calculate the mean

    - finally will fill with the mean

In [26]:
salary=[50000,np.nan,70000,90000]
age=[25,28,30,40]
df=pd.DataFrame(zip(salary,age),
                columns=['Salary','Age'])
df

    Salary  Age
0  50000.0   25
1      NaN   28
2  70000.0   30
3  90000.0   40

- sklearn

    - impute

        - KKNImputer

In [27]:
from sklearn.impute import KNNImputer
imputer = KNNImputer(n_neighbors=2)

pd.DataFrame(imputer.fit_transform(df))

         0     1
0  50000.0  25.0
1  60000.0  28.0
2  70000.0  30.0
3  90000.0  40.0